/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aeropuertogui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author RYZEN
 */
public class ActualizarAeropuerto extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarAeropuerto
     */
    public ActualizarAeropuerto() {
        initComponents();
        llenarCB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelActualizarAeropuerto = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelUbicacion = new javax.swing.JLabel();
        labelSeleccionarAeropuerto = new javax.swing.JLabel();
        cbSeleccionarAeropuerto = new javax.swing.JComboBox<>();
        labelNuevoNombre = new javax.swing.JLabel();
        labelNuevaUbicacion = new javax.swing.JLabel();
        tfNuevoNombre = new javax.swing.JTextField();
        tfNuevaUbicacion = new javax.swing.JTextField();
        btnActualizarAeropuerto = new javax.swing.JButton();
        labelSeleccionNombre = new javax.swing.JLabel();
        labelSeleccionUbicacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        labelActualizarAeropuerto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelActualizarAeropuerto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelActualizarAeropuerto.setText("Actualizar Aeropuerto");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNombre.setText("Nombre:");

        labelUbicacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelUbicacion.setText("Ubicación:");

        labelSeleccionarAeropuerto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSeleccionarAeropuerto.setText("Seleccionar Aeropuerto: ");

        cbSeleccionarAeropuerto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSeleccionarAeropuertoItemStateChanged(evt);
            }
        });

        labelNuevoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNuevoNombre.setText("Nuevo nombre: ");

        labelNuevaUbicacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNuevaUbicacion.setText("Nueva Ubicación:");

        tfNuevoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tfNuevaUbicacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnActualizarAeropuerto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnActualizarAeropuerto.setText("Actualizar");
        btnActualizarAeropuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarAeropuertoActionPerformed(evt);
            }
        });

        labelSeleccionNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSeleccionNombre.setText(" ");

        labelSeleccionUbicacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSeleccionUbicacion.setText(" ");
        labelSeleccionUbicacion.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mantener en blanco si no desea actualizar 1 campo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelActualizarAeropuerto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelSeleccionarAeropuerto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSeleccionarAeropuerto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNuevoNombre)
                                    .addComponent(labelNuevaUbicacion))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNuevaUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                                    .addComponent(tfNuevoNombre)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelUbicacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelSeleccionNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(81, 81, 81))
                                    .addComponent(labelSeleccionUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnActualizarAeropuerto)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelActualizarAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeleccionarAeropuerto)
                    .addComponent(cbSeleccionarAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNombre)
                    .addComponent(labelSeleccionNombre))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUbicacion)
                    .addComponent(labelSeleccionUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNuevoNombre)
                    .addComponent(tfNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNuevaUbicacion)
                    .addComponent(tfNuevaUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnActualizarAeropuerto)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarAeropuerto(){
        
        try(var manager = new DBManager()) {
            
            boolean resp = manager.actualizarAeropuerto(labelSeleccionNombre.getText(), tfNuevoNombre.getText(), tfNuevaUbicacion.getText());
            if (resp) {
                
                llenarCB();
                JOptionPane.showMessageDialog(this,"Aeropuerto Actualizado Correctamente");    
                
            } else {
                JOptionPane.showMessageDialog(this,"Error al Actualizado Aeropuerto","Error",JOptionPane.ERROR_MESSAGE);
                               
            }            
        } catch (SQLException ex) {
            ex.printStackTrace();
            System.out.println("Excepción SQL: " + ex.getMessage());
            System.out.println("Estado SQL: " + ex.getSQLState());
            System.out.println("Código de error: " + ex.getErrorCode());
        }  
    }
    private void cbSeleccionarAeropuertoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSeleccionarAeropuertoItemStateChanged
        
        Object item = cbSeleccionarAeropuerto.getSelectedItem();
        if (item != null){
            String itemSeleccionado = item.toString();
        if (itemSeleccionado == "Seleccionar"){
            labelSeleccionNombre.setText("");
            labelSeleccionUbicacion.setText("");
        } else {
            List<String> aeropuerto =obtenerInfo(itemSeleccionado);
            String nombreAeropuerto = aeropuerto.get(1);
            String ubicacionAeropuerto = aeropuerto.get(2);
            labelSeleccionNombre.setText(nombreAeropuerto);
            labelSeleccionUbicacion.setText(ubicacionAeropuerto);
        }
        }
    }//GEN-LAST:event_cbSeleccionarAeropuertoItemStateChanged

    private void btnActualizarAeropuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAeropuertoActionPerformed
        if (tfNuevoNombre.getText().equals("") && tfNuevaUbicacion.getText().equals("")){
             JOptionPane.showMessageDialog(this,"Debe llenar los campos","Error",JOptionPane.ERROR_MESSAGE);
        } else if (cbSeleccionarAeropuerto.getSelectedItem().toString().equals("Seleccionar")) {
            JOptionPane.showMessageDialog(this,"Debe Seleccionar un aeropuerto","Error",JOptionPane.ERROR_MESSAGE);
            tfNuevoNombre.setText("");
            tfNuevaUbicacion.setText("");
        } else{
            actualizarAeropuerto();
            tfNuevoNombre.setText("");
            tfNuevaUbicacion.setText("");
        }
        
        
        
    }//GEN-LAST:event_btnActualizarAeropuertoActionPerformed

    private List<String> obtenerInfo(String itemSeleccionado){
        List<String> aeropuerto = new ArrayList<>();
        try(var manager = new DBManager()){
            aeropuerto = manager.getInfoAeropuertos(itemSeleccionado);
        }catch(Exception x){
            System.out.println("Error");
        }
        return aeropuerto;
    }
    private void llenarCB() {
        try(var manager = new DBManager()) {
            cbSeleccionarAeropuerto.removeAllItems();
            List<String> aeropuertos = manager.obtenerListaAeropuertos();
            cbSeleccionarAeropuerto.addItem("Seleccionar");
            for (String item : aeropuertos) {
            cbSeleccionarAeropuerto.addItem(item);
        }
        } catch (SQLException ex) {
            ex.printStackTrace();
            System.out.println("Excepción SQL: " + ex.getMessage());
            System.out.println("Estado SQL: " + ex.getSQLState());
            System.out.println("Código de error: " + ex.getErrorCode());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarAeropuerto;
    private javax.swing.JComboBox<String> cbSeleccionarAeropuerto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelActualizarAeropuerto;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNuevaUbicacion;
    private javax.swing.JLabel labelNuevoNombre;
    private javax.swing.JLabel labelSeleccionNombre;
    private javax.swing.JLabel labelSeleccionUbicacion;
    private javax.swing.JLabel labelSeleccionarAeropuerto;
    private javax.swing.JLabel labelUbicacion;
    private javax.swing.JTextField tfNuevaUbicacion;
    private javax.swing.JTextField tfNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
